### ISSUE TITLE
several issues: 1. out of memory, 2. sharing lbcnn AlexNet 

### ISSUE THREAD

**Issue by segilee** [juefeix/lbcnn.torch#6]
1. There is no guide for running lbcnn version resnet with the dataset Imagenet even there r requirements to download the Imagenet data set! What happened? Actually, when I run yr code with Imagenet dataset, there is an error about out of memory even the batch size is small enough. Is it sure that there is no problems for running lbcnn version resnet with the dataset Imagenet?
There is no problem for running fb.resnet with Imagenet.

2. Would you share lbcnn version AlexNet source code for training the dataset of Imagenet?

**Comment by juefeix** [comment]
We didn't run Imagenet on resnet in the paper, hence no guide for running that. We are thinking of incorporating Imagenet experiments in a new pytorch repo, pending permissions from certain parties. I hope you could understand...

**Comment by segilee** [comment]
Thanks for kind replying!
However, there is no commnet on second issues...
In your paper, there is results on full Imagenet with LBCNN version of Alexnet. I want to train its LBCNN version and do some experiments. Please help me juefeix.. Would you share lbcnn version AlexNet source code?

**Comment by segilee** [comment]
Thanks for kind replying!!
I can understand what u mean but U can share at least what you done in the paper, not the progressing one isn't it. I hope you to help.
Thanks.

**Comment by juefeix** [comment]
I wish I could help, but like I said, we are thinking of incorporating Imagenet experiments (old and new) in a new pytorch repo, pending permissions from certain parties. I hope you could understand...
